export default {
  UPDATE_APPDATA: 'UPDATE_APPDATA',
  EXPAND_USER_CATEGORY: 'EXPAND_USER_CATEGORY',
  COLLASPE_USER_CATEGORY: 'COLLASPE_USER_CATEGORY',
  FETCH_USER_CATEGORY_BEGIN: 'FETCH_USER_CATEGORY_BEGIN',
  FETCH_USER_CATEGORY_SUCCESS: 'FETCH_USER_CATEGORY_SUCCESS',
  FETCH_USER_CATEGORY_FAILURE: 'FETCH_USER_CATEGORY_FAILURE',
  FETCH_USERS_BY_FRIEND_CATEGORY_ID_BEGIN: 'FETCH_USERS_BY_FRIEND_CATEGORY_ID_BEGIN',
  FETCH_USERS_BY_FRIEND_CATEGORY_ID_SUCCESS: 'FETCH_USERS_BY_FRIEND_CATEGORY_ID_SUCCESS',
  FETCH_USERS_BY_FRIEND_CATEGORY_ID_FAILURE: 'FETCH_USERS_BY_FRIEND_CATEGORY_ID_FAILURE',
};
