export default {
  UPDATE_APPDATA: 'UPDATE_APPDATA',
  FETCH_USER_CATEGORY_BEGIN: 'FETCH_USER_CATEGORY_BEGIN',
  FETCH_USER_CATEGORY_SUCCESS: 'FETCH_USER_CATEGORY_SUCCESS',
  FETCH_USER_CATEGORY_FAILURE: 'FETCH_USER_CATEGORY_FAILURE'
};
